#!/usr/bin/env bash
#A bash script to install NginX in ubuntu 16.04

sudo apt-get update
sudo apt-get upgrade

sudo apt-get install nginx -y

# Crate a directory called html and file index.html inside the nginx server
sudo mkdir /var/www/html
sudo touch /var/www/html/index.html

# Display your message inside the index file 
sudo echo "Holberton School" > /var/www/html/index.html
sudo service nginx restart
