#!/usr/bin/env bash
#Bash script that installs HAProxy & makes configurations

apt-get -y install software-properties-common
add-apt-repository ppa:vbernat/haproxy-1.8
apt-get update
apt-get -y install haproxy
echo "ENABLED=1" >> /etc/default/haproxy
printf %s "listen 5419-webs
    bind *:80
    mode http
    balance roundrobin
    server 5419-web-01 54.83.75.49:80 check
    server 5419-web-02 34.226.202.215:80 check
" >> /etc/haproxy/haproxy.cfg
sudo service haproxy restart
