#!/usr/bin/env bash
# Configure the Ubuntu container's Nginx to listen on port 80
rm /etc/nginx/sites-enabled/default
ln -s /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default
sudo service nignx restart
