#!/usr/bin/env bash
#A bash script to install NginX in ubuntu 16.04

sudo apt-get update && upgrade
sudo apt-get install nginx -y

# Crate a directory called html inside the nginx server
sudo mkdir /var/www/html

#Create a file inside that directory called index.html
sudo touch /var/www/html/index.html

sudo ufw allow 'Nginx HTTP'

#Display your message then
sudo echo "Holberton School" > /var/www/html/index.html
sudo service nginx restart
