#!/usr/bin/env bash
#Instal Nginx on Ubuntu
#Nginx is listening on port 80
#The GET request should return a page containing "Holberton School"

sudo apt-get update && upgrade
sudo apt-get install nginx -y

#Create a file inside the html directory
echo "Holberton School" | sudo tee /var/www/html/index.nginx-debian.html

sudo service nginx restart 
