#!/usr/bin/env bash
#Redirection

sudo apt-get update
sudo apt-get install nginx -y

sudo echo "Holberton School" > /var/www/html/index.html
sudo echo "Ceci n'est pas une page" > /var/www/html/404.html
sudo printf %s "server {
    listen 80;
    listen [::]:80;
    root   /var/www/html;
    index  index.html;
    location /redirect_me {
        return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;
    }
}" > /etc/nginx/sites-available/default

service nginx restart
