#!/usr/bin/env bash
# Configure nginx server redirecting to another page

sudo apt update
sudo apt -y install nginx
newlines="\\\trewrite ^/redirect_me https://www.youtube.com/watch?v=Ip6cw8gfHHI&ab_channel=d4vdVEVO permanent;"
sudo sed -i "53i $newlines" /etc/nginx/sites-available/default
sudo service nginx restart
